Removed site and wise references from API. Moved announcements to its own class.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -2,19 +2,10 @@
 echo "*****************************"
 echo "* BEGIN WISE PRECOMMIT HOOK *"
 echo "*****************************"
-if [ "`git diff --cached --name-status | grep src/main/webapp/site | wc -l`" -gt 0 ]; then
-  npm run extract-i18n
-  #gulp site-i18n
-  #ng xi18n
-  if [ "`git diff --name-status | awk '$1 == "M"' | grep xlf | wc -l`" -gt 0 ]; then
-    echo "Your code generated changes to the following file(s):"
-    git diff --name-status | awk '$1 == "M"' | grep xlf
-    git add src/main/webapp/site/src/messages.xlf
-    echo "Generated file(s) were added to git for commit"
-    echo "You can commit with -n to bypass this pre-commit hook."
-    echo "Done."
-    exit 0
-  fi
+if [ "`git diff --cached --name-status | grep src/main/resources/application-dockerdev.properties | wc -l`" -gt 0 ]; then
+  echo "Aborting. You are trying to add application-dockerdev.properties. This file may contain confidential data like passwords."
+  echo "If you really want to commit this file, you can commit with -n to bypass this pre-commit hook."
+  exit 1
 fi
 echo "***************************"
 echo "* END WISE PRECOMMIT HOOK *"
